[package]
name = "steel-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
stb_image_write_rust = "1.16.1"

[features]
use_f64 = []
